/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as ImpostazioniNotificheRouteImport } from './routes/impostazioni-notifiche'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as PrevisioniRouteImport } from './routes/previsioni'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProceduresRouteImport } from './routes/procedures'
import { Route as QrRouteImport } from './routes/qr'
import { Route as QuestionarioRouteImport } from './routes/questionario'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ServiziSportiviRouteImport } from './routes/servizi-sportivi'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as TrasportiSecondariRouteImport } from './routes/trasporti-secondari'
import { Route as FeedbackIndexRouteImport } from './routes/feedback.index'
import { Route as GestioneIndexRouteImport } from './routes/gestione.index'
import { Route as GestioneAreaIdRouteImport } from './routes/gestione.$areaId'
import { Route as OperatoriUsernameRouteImport } from './routes/operatori.$username'
import { Route as FeedbackSlugIndexRouteImport } from './routes/feedback.$slug.index'
import { Route as FeedbackSlugCompilaRouteImport } from './routes/feedback.$slug.compila'
import { Route as ApiPublicHooksDailyForceLogoutRouteImport } from './routes/api/public/hooks/daily-force-logout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpostazioniNotificheRoute = ImpostazioniNotificheRouteImport.update({
  id: '/impostazioni-notifiche',
  path: '/impostazioni-notifiche',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const PrevisioniRoute = PrevisioniRouteImport.update({
  id: '/previsioni',
  path: '/previsioni',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProceduresRoute = ProceduresRouteImport.update({
  id: '/procedures',
  path: '/procedures',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionarioRoute = QuestionarioRouteImport.update({
  id: '/questionario',
  path: '/questionario',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiziSportiviRoute = ServiziSportiviRouteImport.update({
  id: '/servizi-sportivi',
  path: '/servizi-sportivi',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TrasportiSecondariRoute = TrasportiSecondariRouteImport.update({
  id: '/trasporti-secondari',
  path: '/trasporti-secondari',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackIndexRoute = FeedbackIndexRouteImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => rootRouteImport,
} as any)
const GestioneIndexRoute = GestioneIndexRouteImport.update({
  id: '/gestione/',
  path: '/gestione/',
  getParentRoute: () => rootRouteImport,
} as any)
const GestioneAreaIdRoute = GestioneAreaIdRouteImport.update({
  id: '/gestione/$areaId',
  path: '/gestione/$areaId',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatoriUsernameRoute = OperatoriUsernameRouteImport.update({
  id: '/operatori/$username',
  path: '/operatori/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackSlugIndexRoute = FeedbackSlugIndexRouteImport.update({
  id: '/feedback/$slug/',
  path: '/feedback/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackSlugCompilaRoute = FeedbackSlugCompilaRouteImport.update({
  id: '/feedback/$slug/compila',
  path: '/feedback/$slug/compila',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDailyForceLogoutRoute =
  ApiPublicHooksDailyForceLogoutRouteImport.update({
    id: '/api/public/hooks/daily-force-logout',
    path: '/api/public/hooks/daily-force-logout',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checklist': typeof ChecklistRoute
  '/dashboard': typeof DashboardRoute
  '/guide': typeof GuideRoute
  '/impostazioni-notifiche': typeof ImpostazioniNotificheRoute
  '/office': typeof OfficeRoute
  '/previsioni': typeof PrevisioniRoute
  '/privacy': typeof PrivacyRoute
  '/procedures': typeof ProceduresRoute
  '/qr': typeof QrRoute
  '/questionario': typeof QuestionarioRoute
  '/report': typeof ReportRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/servizi-sportivi': typeof ServiziSportiviRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/trasporti-secondari': typeof TrasportiSecondariRoute
  '/gestione/$areaId': typeof GestioneAreaIdRoute
  '/operatori/$username': typeof OperatoriUsernameRoute
  '/feedback/': typeof FeedbackIndexRoute
  '/gestione/': typeof GestioneIndexRoute
  '/feedback/$slug/compila': typeof FeedbackSlugCompilaRoute
  '/feedback/$slug/': typeof FeedbackSlugIndexRoute
  '/api/public/hooks/daily-force-logout': typeof ApiPublicHooksDailyForceLogoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checklist': typeof ChecklistRoute
  '/dashboard': typeof DashboardRoute
  '/guide': typeof GuideRoute
  '/impostazioni-notifiche': typeof ImpostazioniNotificheRoute
  '/office': typeof OfficeRoute
  '/previsioni': typeof PrevisioniRoute
  '/privacy': typeof PrivacyRoute
  '/procedures': typeof ProceduresRoute
  '/qr': typeof QrRoute
  '/questionario': typeof QuestionarioRoute
  '/report': typeof ReportRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/servizi-sportivi': typeof ServiziSportiviRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/trasporti-secondari': typeof TrasportiSecondariRoute
  '/gestione/$areaId': typeof GestioneAreaIdRoute
  '/operatori/$username': typeof OperatoriUsernameRoute
  '/feedback': typeof FeedbackIndexRoute
  '/gestione': typeof GestioneIndexRoute
  '/feedback/$slug/compila': typeof FeedbackSlugCompilaRoute
  '/feedback/$slug': typeof FeedbackSlugIndexRoute
  '/api/public/hooks/daily-force-logout': typeof ApiPublicHooksDailyForceLogoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checklist': typeof ChecklistRoute
  '/dashboard': typeof DashboardRoute
  '/guide': typeof GuideRoute
  '/impostazioni-notifiche': typeof ImpostazioniNotificheRoute
  '/office': typeof OfficeRoute
  '/previsioni': typeof PrevisioniRoute
  '/privacy': typeof PrivacyRoute
  '/procedures': typeof ProceduresRoute
  '/qr': typeof QrRoute
  '/questionario': typeof QuestionarioRoute
  '/report': typeof ReportRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/servizi-sportivi': typeof ServiziSportiviRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/trasporti-secondari': typeof TrasportiSecondariRoute
  '/gestione/$areaId': typeof GestioneAreaIdRoute
  '/operatori/$username': typeof OperatoriUsernameRoute
  '/feedback/': typeof FeedbackIndexRoute
  '/gestione/': typeof GestioneIndexRoute
  '/feedback/$slug/compila': typeof FeedbackSlugCompilaRoute
  '/feedback/$slug/': typeof FeedbackSlugIndexRoute
  '/api/public/hooks/daily-force-logout': typeof ApiPublicHooksDailyForceLogoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/checklist'
    | '/dashboard'
    | '/guide'
    | '/impostazioni-notifiche'
    | '/office'
    | '/previsioni'
    | '/privacy'
    | '/procedures'
    | '/qr'
    | '/questionario'
    | '/report'
    | '/reports'
    | '/search'
    | '/security'
    | '/servizi-sportivi'
    | '/sitemap.xml'
    | '/stats'
    | '/trasporti-secondari'
    | '/gestione/$areaId'
    | '/operatori/$username'
    | '/feedback/'
    | '/gestione/'
    | '/feedback/$slug/compila'
    | '/feedback/$slug/'
    | '/api/public/hooks/daily-force-logout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/checklist'
    | '/dashboard'
    | '/guide'
    | '/impostazioni-notifiche'
    | '/office'
    | '/previsioni'
    | '/privacy'
    | '/procedures'
    | '/qr'
    | '/questionario'
    | '/report'
    | '/reports'
    | '/search'
    | '/security'
    | '/servizi-sportivi'
    | '/sitemap.xml'
    | '/stats'
    | '/trasporti-secondari'
    | '/gestione/$areaId'
    | '/operatori/$username'
    | '/feedback'
    | '/gestione'
    | '/feedback/$slug/compila'
    | '/feedback/$slug'
    | '/api/public/hooks/daily-force-logout'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/checklist'
    | '/dashboard'
    | '/guide'
    | '/impostazioni-notifiche'
    | '/office'
    | '/previsioni'
    | '/privacy'
    | '/procedures'
    | '/qr'
    | '/questionario'
    | '/report'
    | '/reports'
    | '/search'
    | '/security'
    | '/servizi-sportivi'
    | '/sitemap.xml'
    | '/stats'
    | '/trasporti-secondari'
    | '/gestione/$areaId'
    | '/operatori/$username'
    | '/feedback/'
    | '/gestione/'
    | '/feedback/$slug/compila'
    | '/feedback/$slug/'
    | '/api/public/hooks/daily-force-logout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ChecklistRoute: typeof ChecklistRoute
  DashboardRoute: typeof DashboardRoute
  GuideRoute: typeof GuideRoute
  ImpostazioniNotificheRoute: typeof ImpostazioniNotificheRoute
  OfficeRoute: typeof OfficeRoute
  PrevisioniRoute: typeof PrevisioniRoute
  PrivacyRoute: typeof PrivacyRoute
  ProceduresRoute: typeof ProceduresRoute
  QrRoute: typeof QrRoute
  QuestionarioRoute: typeof QuestionarioRoute
  ReportRoute: typeof ReportRoute
  ReportsRoute: typeof ReportsRoute
  SearchRoute: typeof SearchRoute
  SecurityRoute: typeof SecurityRoute
  ServiziSportiviRoute: typeof ServiziSportiviRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatsRoute: typeof StatsRoute
  TrasportiSecondariRoute: typeof TrasportiSecondariRoute
  GestioneAreaIdRoute: typeof GestioneAreaIdRoute
  OperatoriUsernameRoute: typeof OperatoriUsernameRoute
  FeedbackIndexRoute: typeof FeedbackIndexRoute
  GestioneIndexRoute: typeof GestioneIndexRoute
  FeedbackSlugCompilaRoute: typeof FeedbackSlugCompilaRoute
  FeedbackSlugIndexRoute: typeof FeedbackSlugIndexRoute
  ApiPublicHooksDailyForceLogoutRoute: typeof ApiPublicHooksDailyForceLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impostazioni-notifiche': {
      id: '/impostazioni-notifiche'
      path: '/impostazioni-notifiche'
      fullPath: '/impostazioni-notifiche'
      preLoaderRoute: typeof ImpostazioniNotificheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/previsioni': {
      id: '/previsioni'
      path: '/previsioni'
      fullPath: '/previsioni'
      preLoaderRoute: typeof PrevisioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedures': {
      id: '/procedures'
      path: '/procedures'
      fullPath: '/procedures'
      preLoaderRoute: typeof ProceduresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionario': {
      id: '/questionario'
      path: '/questionario'
      fullPath: '/questionario'
      preLoaderRoute: typeof QuestionarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servizi-sportivi': {
      id: '/servizi-sportivi'
      path: '/servizi-sportivi'
      fullPath: '/servizi-sportivi'
      preLoaderRoute: typeof ServiziSportiviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trasporti-secondari': {
      id: '/trasporti-secondari'
      path: '/trasporti-secondari'
      fullPath: '/trasporti-secondari'
      preLoaderRoute: typeof TrasportiSecondariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/': {
      id: '/feedback/'
      path: '/feedback'
      fullPath: '/feedback/'
      preLoaderRoute: typeof FeedbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestione/': {
      id: '/gestione/'
      path: '/gestione'
      fullPath: '/gestione/'
      preLoaderRoute: typeof GestioneIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestione/$areaId': {
      id: '/gestione/$areaId'
      path: '/gestione/$areaId'
      fullPath: '/gestione/$areaId'
      preLoaderRoute: typeof GestioneAreaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operatori/$username': {
      id: '/operatori/$username'
      path: '/operatori/$username'
      fullPath: '/operatori/$username'
      preLoaderRoute: typeof OperatoriUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/$slug/': {
      id: '/feedback/$slug/'
      path: '/feedback/$slug'
      fullPath: '/feedback/$slug/'
      preLoaderRoute: typeof FeedbackSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/$slug/compila': {
      id: '/feedback/$slug/compila'
      path: '/feedback/$slug/compila'
      fullPath: '/feedback/$slug/compila'
      preLoaderRoute: typeof FeedbackSlugCompilaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-force-logout': {
      id: '/api/public/hooks/daily-force-logout'
      path: '/api/public/hooks/daily-force-logout'
      fullPath: '/api/public/hooks/daily-force-logout'
      preLoaderRoute: typeof ApiPublicHooksDailyForceLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ChecklistRoute: ChecklistRoute,
  DashboardRoute: DashboardRoute,
  GuideRoute: GuideRoute,
  ImpostazioniNotificheRoute: ImpostazioniNotificheRoute,
  OfficeRoute: OfficeRoute,
  PrevisioniRoute: PrevisioniRoute,
  PrivacyRoute: PrivacyRoute,
  ProceduresRoute: ProceduresRoute,
  QrRoute: QrRoute,
  QuestionarioRoute: QuestionarioRoute,
  ReportRoute: ReportRoute,
  ReportsRoute: ReportsRoute,
  SearchRoute: SearchRoute,
  SecurityRoute: SecurityRoute,
  ServiziSportiviRoute: ServiziSportiviRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatsRoute: StatsRoute,
  TrasportiSecondariRoute: TrasportiSecondariRoute,
  GestioneAreaIdRoute: GestioneAreaIdRoute,
  OperatoriUsernameRoute: OperatoriUsernameRoute,
  FeedbackIndexRoute: FeedbackIndexRoute,
  GestioneIndexRoute: GestioneIndexRoute,
  FeedbackSlugCompilaRoute: FeedbackSlugCompilaRoute,
  FeedbackSlugIndexRoute: FeedbackSlugIndexRoute,
  ApiPublicHooksDailyForceLogoutRoute: ApiPublicHooksDailyForceLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
