REVOKE EXECUTE ON FUNCTION public.has_transports_access(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_area_member(uuid, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_admins_new_survey_response() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.log_audit_event() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.cron_auto_force_logout_rome() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.prevent_force_logout_self_update() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.prevent_job_title_self_update() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.prevent_must_change_password_self_update() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.prevent_phone_self_update() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.prevent_suspension_self_update() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.prevent_username_self_update() FROM anon, authenticated, public;